net:
  n1: 256
  img: [65,65]
  steps: 68
  dir: "D:\\ai intro\\dataset"

train:
  bs: 40
  lr: 0.0001
  opt: "RMSprop" # SGD, RMSprop
  n_epochs: 15
  steps_per_epoch: 555

augumentare:
  rescale: 0.00392156862745098
  rotation_range: 40
  width_shift_range: 0.2
  height_shift_range: 0.2
  shear_range: 0.2
  zoom_range: 0.2
  horizontal_flip: True
  fill_mode: 'nearest'
